language: cpp
sudo: false

matrix:
  include:
  - os: linux
    dist: trusty
    env:
    - CMAKE_EXTRA_FLAGS=-DLS_PROTOBUF_REQUIRED:BOOL=ON
    addons:
      apt:
        sources:
          - george-edison55-precise-backports
        packages:
          - cmake-data
          - cmake
          - protobuf-compiler
          - libprotobuf-dev
          - libprotoc-dev
          - g++-4.8
          - gcc-4.8
  - os: osx
    env:
    - CMAKE_EXTRA_FLAGS=
    addons:
      apt:
        packages:
          - protobuf-compiler
          - libprotobuf-dev
          - libprotoc-dev
          - cmake

before_install:
  # Enforce whitespace guidelines
  - ./scripts/whitespace_check.sh

  # Enforce Leap Motion copyright notice
  - ./scripts/copyright_check.sh

script:
  # Build LeapSerial, run unit tests, and install
  - mkdir b
  - cd b
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=~/leapserial/ ${CMAKE_EXTRA_FLAGS}
  - make -j 4 || make
  - ctest --output-on-failure
  - make install > logfile || cat logfile
  - cpack || (cat _CPack_Packages/Linux/TGZ/InstallOutput.log; exit 3)

after_failure:
  - cat Testing/Temporary/LastTest.log 2> /dev/null
